export const SectorTickerList = [
  { ticker: "SPY", describe: "SP500" },
  { ticker: "XLE", describe: "エネルギー" },
  { ticker: "XLK", describe: "情報技術" },
  { ticker: "SMH", describe: "半導体" },
  { ticker: "IBB", describe: "バイオ" },
  { ticker: "XLV", describe: "ヘルスケア" },
  { ticker: "XLP", describe: "生活必需品" },
  { ticker: "XLU", describe: "公益" },
  { ticker: "XLB", describe: "素材" },
  { ticker: "XLY", describe: "一般消費財" },
  { ticker: "XLF", describe: "金融" },
  { ticker: "XLI", describe: "資本財" },
  { ticker: "XLC", describe: "通信" },
  { ticker: "XLRE", describe: "不動産" },
  { ticker: "XME", describe: "金属・鉱業" },
  { ticker: "XOP", describe: "石油開発" },
  { ticker: "XPH", describe: "医薬品" },
  { ticker: "XRT", describe: "小売" },
  { ticker: "ITA", describe: "航空宇宙" },
  { ticker: "AGG", describe: "国債" },
  { ticker: "GLD", describe: "金" },
  { ticker: "DBA", describe: "農業商品" },
  { ticker: "ICLN", describe: "再エネ" },
];
