import React, { FC } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Nav } from "react-bootstrap";
import { signOut, useSession } from "next-auth/react";

type Props = {
  title: string;
};

const Header: FC<Props> = ({ title }) => {
  const { data: session } = useSession();
  return (
    <div className="header">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes"
        />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className="my-account">
        <p>{session?.user?.email} </p>
        <br />
        <button className="btn btn-primary btn-sm" onClick={() => signOut()}>
          Sign out
        </button>
      </div>
      <Nav className="navbar navbar-expand-lg navbar-dark bg-dark d-none-tb">
        <div className="container-xl">
          <Link href="/" className="navbar-brand f-left main-menu">
            My US Stock Portfolio
          </Link>
          <ul className="navbar-nav mr-auto f-left sub-menu">
            <li className="nav-item">
              <Link href="/asset" className="nav-link">
                Asset
              </Link>
            </li>
            <li className="nav-item">
              <Link href="/dividend" className="nav-link">
                Dividend
              </Link>
            </li>
            <li className="nav-item">
              <Link href="/sector" className="nav-link">
                Sector
              </Link>
            </li>
          </ul>
        </div>
      </Nav>
      <div className="nav-sp">
        <Link href="/">
          <div className="nav-sp-item">
            <Image
              src="/portfolio.png"
              width={60}
              height={60}
              style={{ objectFit: "contain" }}
              alt="logo"
            />
            <p>Home</p>
          </div>
        </Link>
        <Link href="/asset">
          <div className="nav-sp-item">
            <Image
              src="/asset.png"
              width={60}
              height={60}
              style={{ objectFit: "contain" }}
              alt="logo"
            />
            <p>Asset</p>
          </div>
        </Link>
        <Link href="/dividend">
          <div className="nav-sp-item">
            <Image
              src="/dividend.png"
              width={60}
              height={60}
              style={{ objectFit: "contain" }}
              alt="logo"
            />
            <p>Dividend</p>
          </div>
        </Link>
        <Link href="/sector">
          <div className="nav-sp-item">
            <Image
              src="/sector.png"
              width={60}
              height={60}
              style={{ objectFit: "contain" }}
              alt="logo"
            />
            <p>Sector</p>
          </div>
        </Link>
      </div>
    </div>
  );
};

export default Header;
