export type TickerDetail = {
  id: number;
  ticker: string;
  quantity: number;
  getPrice: number;
  price: number;
  priceGets: number;
  priceRate: number;
  dividend: number;
  dividendTime: number;
  dividendFirstTime: number;
  sumOfDividend: number;
  dividendRate: number;
  sector: string;
  usdjpy: number;
  sumOfGetPrice: number;
  sumOfPrice: number;
  balance: number;
  balanceRate: number;
};
